config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get  '/terms',    to: 'static_pages#terms'
  
  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy, :show] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
   @post = Post.find_by(id: params[:post_id])
   @comment = current_user.comments.build(comment_params)
   @comment.save
   flash[:success] = "コメントに登録しました"
   redirect_to @post
  end


  def destroy
    @comment = Comment.find_by(id: params[:id])
    byebug
    @post = Post.find_by(id: @comment.post_id)
    @comment.destroy
    flash[:notice] = "コメントを削除しました"
  end

  private
  
  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment] ) do |form| %>
  <div>
    <%= form.text_area :comment_content %>
  </div>
  <div class="actions">
    <%= form.submit "コメントをする" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <% unless comment.id.nil? %>
    <p><%= link_to "#{comment.user.name}さん", user_path(comment.user.id) %></p>
    <p>コメント：<%= comment.content %></p>
    <% if comment.user == current_user %>
      <p><%= link_to 'コメントを削除する', post_comment_path(comment.post_id, comment.id), method: :delete %></p>
    <% end %>
  <% end %>
<% end %>