config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get  '/terms',    to: 'static_pages#terms'
  
  devise_for :users

  resources :users, only: [:index, :show] do
    member do
      get :following, :followers
    end
  end
  resources :posts, only: [:create, :destroy, :show] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :picture, presence: true
  validate  :picture_size
  
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
    private
    
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user,   only: :destroy
  
  def create
    @post = current_user.posts.build(post_params)
    
    if @post.save
      flash[:success] = "投稿に成功しました。!"
      redirect_to post_path(@post)
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "削除しました。"
    redirect_to  root_url
  end
  
  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @like = Like.new
  end

  private

    def post_params
      params.require(:post).permit(:picture)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_url if @post.nil?
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="col-xs-4" id="post-<%=post.id %>">
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <%= link_to(post_path(post)) do%>
  <span class="picture">
    <%= image_tag post.picture.url if post.picture? %></span>
  <% end %>
  <span class="timestamp">
  　<%= "#{time_ago_in_words(post.created_at)}前" %> 
    <% if current_user == post.user %>
      <%= link_to "削除", post, method: :delete,
                                       data: { confirm: "この投稿を削除しますか?" } %>
    <% end %>
  </span>
</div>

app/views/posts/show.html.erb
<% provide(:title, "投稿詳細") %>
<h3><%= @post.user.name %></h3>
 <%= image_tag @post.picture.url if @post.picture? %>
    <br/>
    いいね件数: <%= @post.likes.count %>
<% if current_user.already_liked?(@post) %>
  <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
<% else %>
  <%= button_to 'いいね', post_likes_path(@post) %>
<% end %>

<div class="comment-form">
  <%= form_for(@comment, url: post_comments_path(@post)) do |f| %>
    <div class="field">
     <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :post_id, value: @post.id %>
      <%= f.text_field :content %>
    </div>
    <div class="field">
      <%= f.submit "コメントを投稿", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

<h>コメント一覧</h>
<% @post.comments.each do |comment| %>
  <div id="comment-<%= comment.id %>">
    <strong><%= comment.content %></strong>
    by <%= link_to(comment.user.name,comment.user) %>
    <% if comment.user == current_user %>
      <%= link_to 'コメントを削除',post_comment_path(@post),method: :delete %>
    <% end %>
  </div>
<% end %>